name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create docker container 
      run: |
        docker login --username ${{ secrets.DOCKER_AUTH_LOGIN }} --password ${{ secrets.DOCKER_AUTH_TOKEN }}
        docker build --tag sparklesh/sparkle-frontend:latest \
        --output type=image,push=true --file ./misc/Dockerfile .
    - name: Push container
      run: docker push sparklesh/sparkle-frontend:latest

