name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker buildx ls
        docker buildx build --platform linux/arm/v7 --tag sparkle-frontend --file ./misc/Dockerfile .
    - name: Create docker container 
      run: |
        docker login --username ${{ secrets.DOCKER_AUTH_LOGIN }} --password ${{ secrets.DOCKER_AUTH_TOKEN }}
        docker tag sparkle-frontend ${{ secrets.DOCKER_AUTH_LOGIN }}/sparkle-frontend 
        docker push ${{ secrets.DOCKER_AUTH_LOGIN }}/sparkle-frontend
